#
# Basic Build Setup
#

sudo: required
dist: trusty
language: c
before_install:
  - sudo apt-get -qqy update && sudo apt-get install fakeroot -qqy
  - git fetch --unshallow
  - sudo ./Autobuild.sh -t raspbianstretch-armhf -o deps
script:
  - sudo ./Autobuild.sh -t raspbianstretch-armhf
