include $(dir $(lastword $(MAKEFILE_LIST))).config.mk

INC=-Ibuild.linux -Isrc

CFLAGS += -g -DENABLE_TRACE=1

CFLAGS  += -Wall -Wwrite-strings -Wno-deprecated-declarations
CFLAGS  += -Wmissing-prototypes
CFLAGS  += -fms-extensions -funsigned-char -fno-strict-aliasing -fcommon

LIBS += -lcheck_pic  -pthread  -lrt -lm -lsubunit

# e.g. make -f Makefile.tests tests EXTRA_CFLAGS=-fsanitize=address EXTRA_LIBS=-fsanitize=address
CFLAGS += $(EXTRA_CFLAGS)
LIBS += $(EXTRA_LIBS)

ifdef COVERAGE
CFLAGS += --coverage
LIBS += -lgcov
endif

DAB    = src/input/dab
RTLSDR = src/input/dab/rtlsdr

TESTS = viterbiTest ficHandlerTest mp4processorTest firecheckTest protectionTest \
        sdr_dab_service_instance_Test input_sdrTest sdr_dab_basic_demodulationTest \
        sdr_fifoTest charsetsTest fib-processorTest

.PHONY: tests clean

clean:
		rm -f tests/*.o tests/*.xml $(addprefix tests/,$(TESTS)) tests/viterbiTest-neu

tests:		$(addprefix tests/,$(TESTS))
		@failed=""; for t in $(TESTS); do \
		  (cd tests && ./$$t) || failed="$$failed $$t"; \
		done; \
		if [ -n "$$failed" ]; then echo "FAILED:$$failed"; exit 1; fi

# test helpers and mocks
tests/%.o:	tests/%.c
		gcc $(INC) -I$(DAB) -I$(RTLSDR) $(CFLAGS) -c $< -o $@

# unit tests
tests/%.o:	tests/input/dab/%.c
		gcc $(INC) -I$(DAB) -I$(RTLSDR) $(CFLAGS) -c $< -o $@

tests/%.o:	tests/input/dab/rtlsdr/%.c
		gcc $(INC) -I$(DAB) -I$(RTLSDR) $(CFLAGS) -c $< -o $@

tests/viterbiTest.o:	tests/input/dab/rtlsdr/viterbi_768/viterbiTest.c
		gcc $(INC) -I$(RTLSDR)/viterbi_768/ $(CFLAGS) -c $< -o $@

# code under test
tests/packet.o:	src/packet.c
		gcc $(INC) $(CFLAGS) -c $< -o $@

tests/%.o:	$(DAB)/%.c
		gcc $(INC) -I$(DAB) $(CFLAGS) -c $< -o $@

tests/ofdmDecoder.o:	$(RTLSDR)/ofdmDecoder.c
		gcc $(INC) -I$(RTLSDR) $(CFLAGS) -DDAB_SINGLE_THREAD -c $< -o $@

tests/%.o:	$(RTLSDR)/%.c
		gcc $(INC) -I$(RTLSDR) $(CFLAGS) -c $< -o $@

tests/%.o:	$(RTLSDR)/viterbi_768/%.c
		gcc $(INC) -I$(RTLSDR)/viterbi_768/ $(CFLAGS) -c $< -o $@

VITERBI    = tests/viterbi-768.o tests/spiral-no-sse.o tests/spiral-neon.o
PROTECTION = tests/protection.o tests/protTables.o $(VITERBI)
SDR_INPUT  = tests/input_sdr.o tests/ficHandler.o tests/phasereference.o tests/sdr_fifo.o \
             tests/fic_protection.o tests/ofdmDecoder.o $(PROTECTION)

tests/viterbiTest:	tests/viterbiTest.o $(VITERBI) tests/utilities.o
		gcc $(CFLAGS) $^ $(LIBS) -o $@

tests/viterbiTest-neu:	tests/viterbiTest.o tests/viterbi-neu.o tests/utilities.o
		gcc $(CFLAGS) $^ $(LIBS) -o $@

tests/ficHandlerTest:	tests/ficHandlerTest.o tests/ficHandler.o tests/fic_protection.o $(PROTECTION) \
			tests/utilities.o tests/fib-processor.o tests/dab_service.o tests/charsets.o
		gcc $(CFLAGS) $^ $(LIBS) -o $@

tests/mp4processorTest:	tests/mp4processorTest.o tests/mp4processor.o tests/utilities.o tests/firecheck.o tests/reed-solomon.o
		gcc $(CFLAGS) $^ $(LIBS) -o $@

tests/firecheckTest:	tests/firecheckTest.o tests/firecheck.o tests/utilities.o
		gcc $(CFLAGS) $^ $(LIBS) -o $@

tests/protectionTest:	tests/protectionTest.o tests/eep_protection.o tests/uep_protection.o $(PROTECTION) tests/utilities.o
		gcc $(CFLAGS) $^ $(LIBS) -o $@

tests/sdr_fifoTest:	tests/sdr_fifoTest.o tests/sdr_fifo.o tests/utilities.o
		gcc $(CFLAGS) $^ $(LIBS) -o $@

tests/charsetsTest:	tests/charsetsTest.o tests/charsets.o
		gcc $(CFLAGS) $^ $(LIBS) -o $@

tests/fib-processorTest:	tests/fib-processorTest.o tests/fib-processor.o tests/dab_service.o tests/charsets.o tests/utilities.o
		gcc $(CFLAGS) $^ $(LIBS) -o $@

tests/sdr_dab_service_instance_Test:	tests/sdr_dab_service_instance_Test.o tests/sdr_dab_service_instance.o \
			tests/mscHandler.o tests/eep_protection.o tests/uep_protection.o $(PROTECTION) \
			tests/utilities.o tests/mp4processor.o tests/firecheck.o tests/reed-solomon.o \
			tests/services.o tests/packet.o tests/streaming.o tests/tvh_thread.o
		gcc $(CFLAGS) $^ $(LIBS) -o $@

tests/input_sdrTest:	tests/input_sdrTest.o $(SDR_INPUT) tests/utilities.o tests/fib-processorMock.o
		gcc $(CFLAGS) $^ $(LIBS) -lfftw3f -o $@

tests/sdr_dab_basic_demodulationTest:	tests/sdr_dab_basic_demodulationTest.o tests/sdr_dab_basic_demodulation.o \
			$(SDR_INPUT) tests/utilities.o tests/fib-processor.o tests/tvh_thread.o tests/dab_service.o tests/charsets.o
		gcc $(CFLAGS) $^ $(LIBS) -lfftw3f -o $@
