include $(dir $(lastword $(MAKEFILE_LIST))).config.mk

INC=-Isrc -Ibuild.linux

CFLAGS += -g -DENABLE_TRACE=1

ifdef $(COVERAGE)
CFLAGS += --coverage
LIBS += -lgcov
endif

clean:
		rm -f tests/*.o tests/viterbiTest tests/viterbiTest-neu tests/ficHandlerTest

tests:		tests/viterbiTest tests/ficHandlerTest
		cd tests && ./viterbiTest
		cd tests && ./ficHandlerTest

tests/utilities.o:	tests/utilities.c
		gcc $(INC) $(CFLAGS) -c tests/utilities.c -o $@

tests/viterbiTest.o:	tests/input/mpegts/rtlsdr/viterbi_768/viterbiTest.c
		gcc $(INC) -Isrc/input/mpegts/rtlsdr/viterbi_768/ $(CFLAGS) -c tests/input/mpegts/rtlsdr/viterbi_768/viterbiTest.c -o $@

tests/viterbi-768.o:	src/input/mpegts/rtlsdr/viterbi_768/viterbi-768.c
		gcc $(INC) -Isrc/input/mpegts/rtlsdr/viterbi_768/ $(CFLAGS) -c src/input/mpegts/rtlsdr/viterbi_768/viterbi-768.c -o $@
		
tests/viterbi-neu.o:	src/input/mpegts/rtlsdr/viterbi_768/viterbi-neu.c
		gcc $(INC) -Isrc/input/mpegts/rtlsdr/viterbi_768/ $(CFLAGS) -c src/input/mpegts/rtlsdr/viterbi_768/viterbi-neu.c -o $@
		
tests/spiral-no-sse.o:	src/input/mpegts/rtlsdr/viterbi_768/spiral-no-sse.c
		gcc $(INC) -Isrc/input/mpegts/rtlsdr/viterbi_768/ $(CFLAGS) -c src/input/mpegts/rtlsdr/viterbi_768/spiral-no-sse.c -o $@
		
tests/spiral-neon.o:	src/input/mpegts/rtlsdr/viterbi_768/spiral-neon.c
		gcc $(INC) -Isrc/input/mpegts/rtlsdr/viterbi_768/ $(CFLAGS) -c src/input/mpegts/rtlsdr/viterbi_768/spiral-neon.c -o $@
		
tests/viterbiTest:		tests/viterbiTest.o tests/viterbi-768.o tests/spiral-no-sse.o tests/spiral-neon.o
		gcc $(CFLAGS) tests/viterbiTest.o tests/viterbi-768.o tests/spiral-no-sse.o tests/spiral-neon.o $(LIBS) -o $@

tests/viterbiTest-neu:	tests/viterbiTest.o tests/viterbi-neu.o
		gcc $(CFLAGS) tests/viterbiTest.o tests/viterbi-neu.o $(LIBS) -o $@


tests/ficHandler.o:	src/input/mpegts/rtlsdr/ficHandler.c
		gcc $(INC) -Isrc/input/mpegts/rtlsdr/ $(CFLAGS) -c src/input/mpegts/rtlsdr/ficHandler.c -o $@

tests/protTables.o:	src/input/mpegts/rtlsdr/protTables.c
		gcc $(INC) -Isrc/input/mpegts/rtlsdr/ $(CFLAGS) -c src/input/mpegts/rtlsdr/protTables.c -o $@

tests/ficHandlerTest.o:	tests/input/mpegts/rtlsdr/ficHandlerTest.c
		gcc $(INC) -Isrc/input/mpegts/rtlsdr/ $(CFLAGS) -c tests/input/mpegts/rtlsdr/ficHandlerTest.c -o $@

tests/fib-processorMock.o:	tests/input/mpegts/rtlsdr/fib-processorMock.c
		gcc $(INC) -Isrc/input/mpegts/rtlsdr/ $(CFLAGS) -c tests/input/mpegts/rtlsdr/fib-processorMock.c -o $@

tests/ficHandlerTest:	tests/ficHandlerTest.o tests/ficHandler.o tests/viterbi-768.o tests/spiral-no-sse.o tests/spiral-neon.o tests/protTables.o tests/utilities.o tests/fib-processorMock.o
		gcc $(CFLAGS) tests/ficHandlerTest.o tests/ficHandler.o tests/viterbi-768.o tests/spiral-no-sse.o tests/spiral-neon.o tests/protTables.o tests/utilities.o tests/fib-processorMock.o $(LIBS) -o $@
